# docker network create atelier3
networks:
  atelier3:
    external: true

version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-atelier3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
    driver: local
